### ISSUE TITLE
License would be nice to know ;)

### ISSUE THREAD

**Issue by MorrisJobke** [PVince81/qrgenplasmoid#1]

**Comment by PVince81** [comment]
GPLv3

But I might drop this projet soon. I saw screenshots of Plasma 5.3 where the clipboard app seems to already have a QR code generator, which obsoletes this.

**Comment by PVince81** [comment]
The license is stated here https://github.com/PVince81/qrgenplasmoid/blob/master/doc/LICENSE and in the README. Where did you miss it ? :wink:

**Comment by MorrisJobke** [comment]
-.- sorry, I'm use to have the licence as last item in the readme :P
